- name: Развертка инфраструктуры
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p external@bastion'"
  
  tasks:
  - name: "Установка и настройка nginx на {{ item }}"
    hosts: "{{ item }}"
    loop:
      - web-server-1.ru-central1.internal
      - web-server-2.ru-central1.internal
    tasks:
      - name: Установка nginx
        apt:
          name: nginx
          state: present

      - name: Выключение стандартной конфигурации
        file:
          path: /etc/nginx/sites-enabled/default
          state: absent

      - name: Копирование архива с контентом сайта
        copy:
          src: ./website/content.tar
          dest: /var/www/website/content.tar

      - name: Извлечение содержимого архива
        unarchive:
          src: /var/www/website/content.tar
          dest: /var/www/website/
          remote_src: yes

      - name: Установка прав для файлов сайта
        file:
          path: /var/www/website
          state: directory
          owner: www-data
          group: www-data
          recurse: yes

      - name: Создание конфигурации nginx
        template:
          src: ./website/website.conf.j2
          dest: /etc/nginx/sites-available/website.conf

      - name: Применение конфигурации nginx
        file:
          src: /etc/nginx/sites-available/website.conf
          dest: /etc/nginx/sites-enabled/website.conf
          state: link

      - name: Перезапуск nginx
        service:
          name: nginx
          state: restarted

  - name: Установка zabbix-frontend
    hosts: zabbix-web.ru-central1.internal
    tasks:
      - name: Установка пакетов для zabbix-web
        apt:
          name:
            - zabbix-frontend-php
            - zabbix-apache-conf
          state: present

  - name: Установка zabbix-server
    hosts: zabbix-server.ru-central1.internal
    tasks:
      - name: Установка пакетов для zabbix-server
        apt:
          name: zabbix-server-mysql
          state: present

      - name: Настройка zabbix-server
        template:
          src: templates/zabbix_server.conf.j2
          dest: /etc/zabbix/zabbix_server.conf

