- name: Установка и настройка
  hosts: bastion.ru-central1.internal
  become: yes
  tasks:
    - name: Установка nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Копирование файла конфигурации
      copy:
        src: ../templates/bastion-web.conf.j2
        dest: /etc/nginx/sites-available/bastion-web.conf
        mode: '0644'
    
    - name: Создание каталога
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: Копирование сертификата
      copy:
        src: ../files/private/fullchain.cer
        dest: /etc/nginx/ssl/fullchain.cer
        owner: www-data
        group: www-data
        mode: '0600'

    - name: Копирование ключа
      copy:
        src: ../files/private/sys34-ulovkinp.run.place.key
        dest: /etc/nginx/ssl/sys34-ulovkinp.run.place.key
        owner: www-data
        group: www-data
        mode: '0600'

    - name: Создание сим-линка в sites-enabled
      file:
        src: /etc/nginx/sites-available/bastion-web.conf
        dest: /etc/nginx/sites-enabled/bastion-web.conf
        state: link

    - name: Удаление сайта по умолчанию
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      ignore_errors: yes

    - name: Запуск сервиса nginx
      systemd:
        name: nginx
        enabled: yes
        state: restarted