  - name: Install Elasticsearch
    hosts: elastic
    tasks:
      - name: Install Elasticsearch
        apt:
          name: elasticsearch
          state: present

      - name: Configure Elasticsearch
        template:
          src: templates/elasticsearch.yml.j2
          dest: /etc/elasticsearch/elasticsearch.yml

      - name: Restart Elasticsearch
        service:
          name: elasticsearch
          state: restarted