- name: Установка и настройка elasticsearch
  hosts: elastic.ru-central1.internal

  tasks:

    - name: Скопировать установочный пакет
      copy:
        src: ../files/large/elasticsearch-8.17.0-amd64.deb
        dest: /tmp/elasticsearch.deb

    - name: Установить пакет
      apt:
        deb: /tmp/elasticsearch.deb
        state: present

    - name: Удалить временный файл
      file:
        path: /tmp/elasticsearch.deb
        state: absent

    - name: Перезапустить сервис elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
        enabled: yes