- name: Установка и настройка filebeat
  hosts: 
    - web-server-1.ru-central1.internal
    - web-server-2.ru-central1.internal
  vars_files:
    - ../private/vars.yml
    
  tasks:

    - name: Скопировать установочный пакет
      copy:
        src: ../files/large/filebeat-8.17.0-amd64.deb
        dest: /tmp/filebeat.deb

    - name: Установить пакет
      apt:
        deb: /tmp/filebeat.deb
        state: present

    - name: Удалить временный файл
      file:
        path: /tmp/filebeat.deb
        state: absent

    - name: Копирование конфигурационного файла
      copy:
        src: ../templates/filebeat.conf.j2
        dest: /etc/filebeat/filebeat.conf
        mode: '0666'

    - name: Перезапустить сервис filebeat
      systemd:
        name: filebeat
        state: restarted
        enabled: yes