- name: Установка и настройка filebeat
  hosts: 
    - web-server-1.ru-central1.internal
    - web-server-2.ru-central1.internal
  vars_files:
    - ../private/vars.yml

  tasks:

    - name: Скопировать установочный пакет
      copy:
        src: ../files/large/filebeat-8.17.0-amd64.deb
        dest: /tmp/filebeat.deb

    - name: Установить пакет
      apt:
        deb: /tmp/filebeat.deb
        state: present

    - name: Удалить временный файл
      file:
        path: /tmp/filebeat.deb
        state: absent

    - name: Копирование файла настроек
      template:
        src: ../templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: Сменить пароль elastic
      shell: sudo filebeat modules enable nginx

    - name: Перезапустить сервис filebeat
      systemd:
        name: filebeat
        state: restarted
        enabled: yes