- name: Установка и настройка kibana
  hosts: kibana.ru-central1.internal
  vars:
    kibana_config: /etc/kibana/kibana.yml

  tasks:
    - name: Определить внутренний IP хоста
      set_fact:
        host_interface_ip: "{{ ansible_all_ipv4_addresses | select('search', '^10\\.') | list | first }}"

    - name: Скопировать пакет установки
      copy:
        src: ../files/large/kibana-8.17.0-amd64.deb
        dest: /tmp/kibana.deb

    - name: Установить пакет
      apt:
        deb: /tmp/kibana.deb
        state: present

    - name: Удалить файл пакета
      file:
        path: /tmp/kibana.deb
        state: absent

    - name: Конфигурация kibana
      block:
        - name: Указать порт прослушивания Kibana
          lineinfile:
            path: "{{ kibana_config }}"
            regexp: '^#?server.port: '
            line: "server.port: 5601"
            state: present

        - name: Указать интерфейс прослушивания Kibana
          lineinfile:
            path: "{{ kibana_config }}"
            regexp: '^#?server.host: '
            line: "server.host: {{ host_interface_ip }}"
            state: present

        - name: Указать префикс url Kibana
          lineinfile:
            path: "{{ kibana_config }}"
            regexp: '^#?server.basePath: '
            line: "server.basePath: \"/kibana\""
            state: present

    - name: Перезапустить сервис Kibana
      systemd:
        name: kibana
        state: restarted
        enabled: yes