- name: Запуск задач установки
  hosts: all

  tasks:

- import_playbook: zabbix-agent.yml
  vars:
    zabbix_agent_config: "/etc/zabbix/zabbix_agent2.conf"

- import_playbook: zabbix-server.yml

- import_playbook: web-servers.yml

- import_playbook: bastion-web.yml

- import_playbook: zabbix-server-api.yml
  vars:
    zabbix_url: "http://localhost/api_jsonrpc.php"

- import_playbook: kibana.yml
  vars:
    kibana_config: /etc/kibana/kibana.yml

- import_playbook: elasticsearch.yml

- import_playbook: kibana-elastic.yml