- name: Запуск задач установки
  hosts: all

  tasks:

# - import_playbook: zabbix-agent.yml
#   vars:
#     zabbix_server: "zabbix.ru-central1.internal"
#     zabbix_agent_config: "/etc/zabbix/zabbix_agent2.conf"
#     zabbix_host_metadata: "managed-host"

# - import_playbook: zabbix-server.yml

# - import_playbook: web-servers.yml

# - import_playbook: bastion-web.yml

- import_playbook: zabbix-server-api.yml
  vars:
    zabbix_url: "http://localhost/api_jsonrpc.php"
    zabbix_user: "Admin"
    zabbix_password: "zabbix"
    rule_name: "Auto registration for managed hosts"
    host_metadata: "managed-host"
    group_name: "Linux Servers"
    template_name: "Linux by Zabbix agent"

# - import_playbook: kibana.yml
#   vars:
#     kibana_config: /etc/kibana/kibana.yml
#     kibana_server_port: "5601"

# - import_playbook: elasticsearch.yml