---
- name: Установка и настройка zabbix-server + postgresql
  hosts: zabbix.ru-central1.internal
  become: yes
  vars:
    zabbix_server_name: "zabbix.sys34-ulovkinp.run.place"
  vars_files:
    - ../private/vars.yml

  tasks:
    - name: Скачать пакет zabbix release
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb"
        dest: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"

    - name: Установить пакет Zabbix release
      apt:
        deb: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"
        state: present

    - name: Установить требуемые пакеты
      apt:
        name:
          - nginx
          - postgresql
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - zabbix-agent2
          - php8.2-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - python3-psycopg2
          - acl
          - python3-bcrypt
        state: present
        update_cache: yes

    - name: Проверить состояние postgresql
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Подготовка базы данных PostgreSQL
      become: true
      become_user: postgres
      block:
        - name: Создать пользователя СУБД
          postgresql_user:
            name: "{{ zabbix_db }}"
            password: "{{ db_password }}"
            state: present

        - name: Создать базу данных
          postgresql_db:
            name: "{{ zabbix_db }}"
            owner: "{{ zabbix_db }}"
            state: present

    - name: Импортировать шаблон в базу данных
      shell: "zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix"
    
    - name: Изменить пароль пользователя Admin
      shell: |
        alias bcryptgen='python3 -c "import bcrypt, sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt()).decode())"'
        PASS=$(bcryptgen {{ manager_password }})
        sudo -u zabbix psql zabbix -c "UPDATE users SET passwd = '$PASS' WHERE username = 'Admin';"

    - name: zabbix-server - пароль базы данных
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^#? DBPassword="
        line: "DBPassword={{ db_password }}"

    - name: zabbix-server - ip для прослушивания
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^#? ListenIP="
        line: "ListenIP={{ zabbix_internal_ip }}"

    - name: nginx - порт веб-интерфейса
      lineinfile:
        path: /etc/zabbix/nginx.conf
        regexp: "^#? *listen "
        line: "listen 80;"

    - name: nginx - имя сервера
      lineinfile:
        path: /etc/zabbix/nginx.conf
        regexp: "^#? *server_name "
        line: "server_name _;"


    - name: Активировать конфигурацию nginx
      file:
        src: /etc/zabbix/nginx.conf
        dest: /etc/nginx/sites-enabled/nginx.conf
        state: link

    - name: Удалить сайт по умолчанию
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      ignore_errors: yes

    - name: Скопировать конфигурацию zabbix php
      template:
        src: ../templates/zabbix-server-php.conf.j2
        dest: /etc/zabbix/web/zabbix.conf.php
        mode: '0644'

    - name: Перезапустить сервисы
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - nginx
        - zabbix-server
        - zabbix-agent2
