---
- name: Add autoregistration rule in Zabbix for Linux servers
  gather_facts: no
  hosts:
    - zabbix.ru-central1.internal

  tasks:
    - name: Authenticate to Zabbix API
      uri:
        url: "{{ zabbix_url }}"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_password }}"
          id: 1
        body_format: json
        return_content: yes
      register: auth_response

    - name: Extract auth token
      set_fact:
        zabbix_auth_token: "{{ auth_response.json.result }}"

    - name: Create autoregistration action for Linux servers
      uri:
        url: "{{ zabbix_url }}"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "action.create"
          params:
            name: "Register Linux servers"
            eventsource: "2"
            filter:
              evaltype: "2"
              conditions:
                - conditiontype: "24"
                  operator: "2"
                  value: "managed-host"
            operations:
              - operationtype: "4"
                opgroup:
                  - groupid: "2"
              - operationtype: "6"
                optemplate:
                  - templateid: "10001"
        headers:
          Authorization: "Bearer {{ zabbix_auth_token }}"
        body_format: json
        return_content: yes
      register: action_create_response

    - name: Show action creation response
      debug:
        msg: "{{ action_create_response }}"
