---
- name: Установка zabbix-agent2
  hosts: all
  vars:
    zabbix_agent_config: "/etc/zabbix/zabbix_agent2.conf"
    web_hosts:
      - web-server1.ru-central1.internal
      - web-server2.ru-central1.internal
  vars_files:
    - ../private/vars.yml
    
  tasks:
    - name: Определение внутреннего IP хоста
      set_fact:
        host_interface_ip: "{{ ansible_all_ipv4_addresses | select('search', '^10\\.') | list | first }}"
        
    - name: Скачать пакет zabbix release
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb"
        dest: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"

    - name: Установить пакет zabbix release
      apt:
        deb: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"
        state: present

    - name: Обновить репозиторий apt
      apt:
        update_cache: yes

    - name: Установить zabbix-agent2, mc (ну чисто для меня)
      apt:
        name:
          - zabbix-agent2
          - mc
        state: present

    - name: Обновить конфигурацию zabbix-agent2
      block:
        - name: Указать сервер Zabbix
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: '^Server='
            line: "Server={{ zabbix_server }}"
            state: present

        - name: Указать активный сервер Zabbix
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: '^ServerActive='
            line: "ServerActive={{ zabbix_server }}"
            state: present

        - name: Исключить параметр Hostname
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: 'Hostname='
            line: "#Hostname="
            state: present

        - name: Указать параметр HostnameItem
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: '^#? ?HostnameItem='
            line: "HostnameItem=system.hostname"
            state: present

        - name: Указать параметр Metadata
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: '^#? ?HostMetadata='
            line: "HostMetadata={{ zabbix_host_metadata }}"
            state: present
          when: ansible_fqdn not in web_hosts

        - name: Указать параметр Metadata
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: '^#? ?HostMetadata='
            line: "HostMetadata=managed-host-nginx"
            state: present
          when: ansible_fqdn in web_hosts

        - name: Указать параметр HostInterface
          lineinfile:
            path: "{{ zabbix_agent_config }}"
            regexp: '^#? ?HostInterface='
            line: "HostInterface={{ host_interface_ip }}"
            state: present
      when: ansible_fqdn != "zabbix.ru-central1.internal"

    - name: Установить путь для логов
      lineinfile:
        path: "{{ zabbix_agent_config }}"
        regexp: '^LogFile='
        line: "LogFile=/var/log/zabbix/zabbix_agentd.log"
        state: present

    - name: Перезапустить сервис zabbix-agent2
      systemd:
        name: zabbix-agent2
        state: restarted
        enabled: yes
