---
- name: Add autoregistration rule in Zabbix
  gather_facts: no
  hosts:
    - zabbix.ru-central1.internal

  tasks:
    - name: Authenticate to Zabbix API
      uri:
        url: "{{ zabbix_url }}"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_password }}"
          id: 1
        body_format: json
        return_content: yes
      register: auth_response

    - name: Set authentication token
      set_fact:
        zabbix_auth_token: "{{ auth_response.json.result }}"

    - name: Create autoregistration action
      community.zabbix.zabbix_action:
        http_login_user: "{{ zabbix_user }}"
        http_login_password: "{{ zabbix_password }}"
        name: "{{ rule_name }}"
        event_source: auto_registration
        status: enabled
        conditions:
          - type: host_metadata
            operator: equals
            value: "{{ host_metadata }}"
        operations:
          - type: add_to_host_group
            host_groups:
              - "{{ group_name }}"
          - type: link_to_template
            templates:
              - "{{ template_name }}"
        state: present
