---
- name: Создание правила авторегистрации для хостов
  gather_facts: no
  hosts:
    - zabbix.ru-central1.internal
  vars_files:
    - ../private/vars.yml
    
  tasks:
    - name: Получить токен пользователя по умолчанию
      uri:
        url: "{{ zabbix_url }}"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_password }}"
          id: 1
        body_format: json
        return_content: yes
      register: auth_response

    - name: Извлечь токен в переменную
      set_fact:
        zabbix_auth_token: "{{ auth_response.json.result }}"

    - name: Создать правило авторегистрации
      uri:
        url: "{{ zabbix_url }}"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "action.create"
          params:
            name: "Регистрация хостов по значению метаданных"
            eventsource: "2"
            filter:
              evaltype: "2"
              conditions:
                - conditiontype: "24"
                  operator: "2"
                  value: "{{ zabbix_host_metadata }}"
            operations:
              - operationtype: "4"
                opgroup:
                  - groupid: "2"
              - operationtype: "6"
                optemplate:
                  - templateid: "10001"
        headers:
          Authorization: "Bearer {{ zabbix_auth_token }}"
        body_format: json

    - name: Создать пользователя manager
      uri:
        url: "{{ zabbix_url }}"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "user.create"
          params:
            username: "manager"
            passwd: "{{ manager_password }}"
            usrgrps:
              - usrgrpid: "3"
        headers:
          Authorization: "Bearer {{ zabbix_auth_token }}"
        body_format: json